### ISSUE TITLE
expiresAt is undefined

### ISSUE THREAD

**Issue by ma-groundspeed** [switch-ch/meteor-accounts-oidc#18]
Looks like you meant to pass expiresAt to the getUserInfoFromEndpoint function.  Throwing an error expireAt is undefined:
https://github.com/switch-ch/meteor-accounts-oidc/blob/master/packages/switch_oidc/oidc_server.js#L150

Passing it down seems to solve the problem.

**Comment by valerytschopp** [comment]
Hi @ma-groundspeed can please make a pull request for this?

**Comment by ma-groundspeed** [comment]
Done

**Comment by paolo** [comment]
Hi, I'm still seeing this issue, but I guess it's cause there was no version bump, so `meteor add switch:accounts-oidc` is still getting the bug...

**Comment by valerytschopp** [comment]
I've bump version to 1.0.7 and publish both packages to atomsphere. It should work now.
